spring:
  application:
    name: TripMingle
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.url}
    username: ${database.name}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: ${jwt.secret-key}
    access-token-expiration: 6000000000000
    refresh-token-expiration: 86400000
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: true
oauth2:
  kakao:
    infoUrl: https://kapi.kakao.com
    baseUrl: https://kauth.kakao.com
    clientId: ${kakao.rest-api-key}
    secretKey: ${kakao.client-secret}
    grant_type: authorization_code
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  servlet:
    session:
      timeout: 30s

springdoc:
  packages-to-scan: com
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

cors:
  allowed-origins: ${allowed-origins}

cloud:
  aws:
    s3:
      bucket: tripmingles3
    credentials:
      accessKey: ${access-key}
      secretKey: ${secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false