name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build With Gradle
        run: ./gradlew build -x test
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: tripmingleApplicationServer
          path: build/libs/tripmingleApplicationServer-0.0.1-SNAPSHOT.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: tripmingleApplicationServer
          path: build/libs/

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${EC2_SSH_KEY}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/tripmingleApplicationServer-0.0.1-SNAPSHOT.jar ${EC2_USERNAME}@${EC2_HOST}:/home/${EC2_USERNAME}/tripmingleApplicationServer.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_HOST} << 'EOF'
            pgrep java | xargs kill -9
            nohup java -jar /home/${EC2_USERNAME}/trelloServer.jar > /home/${EC2_USERNAME}/app.log 2>&1 &
          EOF
          rm -f private_key.pem